### ISSUE TITLE
Dear Soller, Start behaving like an OSHW developer if you want to be one

### ISSUE THREAD

**Issue by Kreyren** [system76/virgo#12]
@jackpot51 You seem to claim that this will be [the most open modern x86 motherboard design](https://fosstodon.org/@soller/110697772188786089), but it's been over a year and the project is just a kicad project file with some bare minimal schematics and gerbers with placed footprints without routing while constantly shilling the project on foostodon.. This is not open-source hardware behavior it's proprietary with extra steps.

Sync the changes and engage with the community on the decisions on what components to use and how to address the problems and overall lead the project as if it was OSHW project with full transparency instead of it being internal-only.

**Comment by leviport** [comment]
What you see in this repo is the current state of the project. Your assumption that progress has continued, but we've kept it to ourselves, is erroneous and highly uncharitable. 

While this github org doesn't have its own code of conduct, you should assume that the one in the Pop!\_OS org applies to this one as well: https://github.com/pop-os/code-of-conduct. Your accusatory post is in breach of rules 1 and 4. You will receive no further warnings.

**Comment by Kreyren** [comment]
> Your assumption that progress has continued, but we've kept it to ourselves, is erroneous and highly uncharitable. -- @leviport (https://github.com/system76/virgo/issues/12#issuecomment-2247951470)

Seems clearly evident considering what was posted in https://fosstodon.org/@soller/110708176613574187 (and other posts..) which appears to be just an information post about what decisions were taken internally as neither of this seemed to have been discussed outside of System76 and i couldn't find any kind of engagement with the community on this project.

The motivation to bring this up as an issue is that getting footprints and documentation to make OSHW x86 systems is very difficult to do in an OSHW-friendly way where it seems that S76 wants to address this which would enable more projects alike so not engaging with the community is quite unfortunate.

Also i would like to work on this project as it's integration is very appealing for OSHW servers and portable [sunshines](https://github.com/LizardByte/Sunshine) in [NiXium](https://github.com/nixium-org/nixium)

> While this github org doesn't have its own code of conduct, you should assume that the one in the Pop!_OS org applies to this one as well: [pop-os/code-of-conduct](https://github.com/pop-os/code-of-conduct). Your accusatory post is in breach of rules 1 and 4. You will receive no further warnings. -- @leviport (https://github.com/system76/virgo/issues/12#issuecomment-2247951470)

Do you really feel like this is an appropriate sentence to sent? It's threatening, toxic and bad taste.
I submitted what i believe is a valid and objective criticism and you decided to be an asshole and trying to make me feel small by making it seem like if i say anything slightly negative about S76 that there will be negative consequences.

Seriously.. what the fuck is wrong with you, please reflect on your actions prior to writing any more comments. OSHW community benefits the best when everyone is treated equally without a guy who feels like they run the whole show.

**Comment by leviport** [comment]
I can tell you're worked up, so I will not block you for the additional CoC violations you racked up in that reply. So I guess I lied, because this one is actually the final warning. This thread is locked. We welcome additional involvement, but you must abide by our CoC.

Asserting that System76 doesn't engage with the community is utter nonsense, as evidenced by all of our other projects. They speak for themselves, so I don't even feel the need to elaborate on this point.

I understand that the incompleteness of the Virgo project is frustrating, but accusations of obfuscation and "not acting like an OSHW developer" are not conducive to healthy collaboration. You could have just asked if this repo is up-to-date with the latest progress (the answer is yes).

Please, take a walk, come back later, and we'd love to consider any input you have on this project. It is still very young, and it's currently not our top priority, so community involvement would be very welcome. I do not wish to be a tyrant, but I will probably resemble one to any who disrespects my colleagues and breaks our CoC.

Edit: I nearly forgot to point out that we have, in fact, been taking community suggestions for the Virgo project for the last five years: https://github.com/system76/laptop-suggestions/. And yes, I read every single one of them.
